### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nkast** [flyingdevelopmentstudio/PVRTexLibNET#1]
@prollin @KonajuGames 
I noticed PVRTexLibNET doesn't define license terms.

@tomspilman
Doesn't the source code comes from Sickheadgames?
https://github.com/SickheadGames/ManagedPVRTC

**Comment by tomspilman** [comment]
We intended our lib to be non-viral open source... we just never added one.  So anything not GPL pretty much.

**Comment by prollin** [comment]
@tomspilman @nkast Super late reply but is this still an issue? What license would make sense?

**Comment by nkast** [comment]
It's an issue with redistributing MGCB & pipeline.

**Comment by prollin** [comment]
Added MIT license; let me know if something else is needed
